### ISSUE TITLE
Problem compiling swiftExample with pods

### ISSUE THREAD

**Issue by sebastian-ruiz** [boundsj/ObjectiveDDP#120]
I can compile the objective-c example just fine. However when doing the following:

```
cd Example/swiftExample/
pod install
```

I receive the following error:

```
Analyzing dependencies
Pre-downloading: `ObjectiveDDP` from `https://github.com/boundsj/ObjectiveDDP.git`, branch `master`
[!] Unable to satisfy the following requirements:

- `ObjectiveDDP (from `https://github.com/boundsj/ObjectiveDDP.git`, branch `master`)` required by `Podfile`
- `ObjectiveDDP (= 0.1.4)` required by `Podfile.lock`
```

I attempted using the Podfile from the objective-c example, and removing Podfile.lock, however this resulted in a multitude of errors in Xcode, see the screenshot below:

![screen shot 2014-12-24 at 12 18 21](https://cloud.githubusercontent.com/assets/2012398/5548353/04165576-8b67-11e4-8efa-fce8bcc5ea59.png)

Thanks very much!

**Comment by trevorbroad** [comment]
I'm getting the same as above, what to do?

**Comment by trevorbroad** [comment]
Using Vephinx's suggestion worked, is there any issue with using the Objective-C's podfile?

**Comment by karlml** [comment]
I have the same problem:

Analyzing dependencies
Pre-downloading: `ObjectiveDDP` from `https://github.com/boundsj/ObjectiveDDP.git`, branch `master`
[!] Unable to satisfy the following requirements:

- `ObjectiveDDP (from `https://github.com/boundsj/ObjectiveDDP.git`, branch `master`)` required by `Podfile`
- `ObjectiveDDP (= 0.1.4)` required by `Podfile.lock`

**Comment by mave99a** [comment]
make sure you have: 

platform :ios, '7.1'
