### ISSUE TITLE
Error cloning app with ObjectiveDDP

### ISSUE THREAD

**Issue by bitomule** [boundsj/ObjectiveDDP#125]
I get this error when I try to clone my app in another computer. Any idea on why this happens?

No submodule mapping found in .gitmodules for path 'Pods/ObjectiveDDP'

Thanks!

**Comment by mikey0000** [comment]
Looks like you need to check out your submodules from git or run pod install

On February 5, 2015 5:40:38 AM GMT+13:00, bitomule <notifications@github.com> wrote:
>I get this error when I try to clone my app in another computer. Any
>idea on why this happens?
>
>No submodule mapping found in .gitmodules for path 'Pods/ObjectiveDDP'
>
>Thanks!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/boundsj/ObjectiveDDP/issues/125

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mikey0000** [comment]
Or you've added a submodule then removed it and left some configuration for it in .gitmodules

**Comment by bitomule** [comment]
I just run a command to remove that submodule and then added it to my gitignore. Seems like it's working fine now.
