### ISSUE TITLE
Issue with SRWebSocket

### ISSUE THREAD

**Issue by bitomule** [boundsj/ObjectiveDDP#129]
I've a random issue with SRWebSocket throwing an EXC_BAD_ACCESS error in my app. The error is in:

    - (void)_handleMessage:(id)message
    {
        SRFastLog(@"Received message");
        [self _performDelegateBlock:^{
            [self.delegate webSocket:self didReceiveMessage:message];
        }];
    }

In the line where it calls didReceiveMessage

It could be related to this issue in SocketRocket:
https://github.com/square/SocketRocket/issues/78

Any idea?

**Comment by mikey0000** [comment]
Is meteorClient in your appDelegate? if not that is your problem.

**Comment by bitomule** [comment]
I've moved meteorClient to app delegate, I had it in a different class.

Thanks!
