### ISSUE TITLE
meteor.signupWithUserParameters

### ISSUE THREAD

**Issue by ducmaxime** [boundsj/ObjectiveDDP#130]
Hello, I want to Signup with this parameters : email, password, username, firstName, lastName.
How to use meteor.signupWithUserParameters function for this ?

Thanks

**Comment by mikey0000** [comment]
This is how, there will be a method added soon to do this without resorting to using UserParameters
```

 @{ @"username": username,@"email": email,
              @"password": @{ @"digest": [self sha256:password], @"algorithm": @"sha-256" },
              @"profile": @{ @"first_name": firstName,
                             @"last_name": lastName,
                             @"signupToken": @""
                          } };

```

**Comment by ducmaxime** [comment]
Hello, thanks but I want to use with SWIFT ?
Can you give me exemple ?

**Comment by mikey0000** [comment]
Have a go first. 

On April 10, 2015 6:36:26 PM GMT+12:00, ducmaxime <notifications@github.com> wrote:
>Hello, thanks but I want to use with SWIFT ?
>Can you give me exemple ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/boundsj/ObjectiveDDP/issues/130#issuecomment-91451440

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by ducmaxime** [comment]
Sorry but I am a begginer and for me your exemple is Objective-C . :( 
I use correctly this function : 
meteor.signupWithUsernameAndEmail(emailTextField.text, email: emailTextField.text, password: passwordTextField.text, fullname: firstNameTextField.text,  responseCallback: {(response, error) -> Void in
				if((error) != nil)
				{
                self.handleFailedAuth(error)
                return
				}
				self.handleSuccessfulAuth()
			})

But can you give me complete exemple with signupWithUserParameters in swift ?

**Comment by mikey0000** [comment]
I'll pull in the method for doing it tomorrow and reply here with it :) all good. It just helps to show you've tried, also gitter is a better place for questions like these. 

On April 10, 2015 7:34:50 PM GMT+12:00, ducmaxime <notifications@github.com> wrote:
>Sorry but I am a begginer and for me your exemple is Objective-C . :( 
>I use correctly this function : 
>meteor.signupWithUsernameAndEmail(emailTextField.text, email:
>emailTextField.text, password: passwordTextField.text, fullname:
>firstNameTextField.text,  responseCallback: {(response, error) -> Void
>in
>				if((error) != nil)
>				{
>                self.handleFailedAuth(error)
>                return
>				}
>				self.handleSuccessfulAuth()
>			})
>
>But can you give me complete exemple with signupWithUserParameters in
>swift ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/boundsj/ObjectiveDDP/issues/130#issuecomment-91467631

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by ducmaxime** [comment]
Ok thank you !!!

**Comment by mikey0000** [comment]
method is up, pull in from master.

**Comment by ducmaxime** [comment]
Hello, Thank you for update but i can't find the new function ? What 's the name of function ?

**Comment by mikey0000** [comment]
It's on the readme 

On April 14, 2015 9:24:25 PM GMT+12:00, ducmaxime <notifications@github.com> wrote:
>Hello, Thank you for update but i can't find the new function ? What 's
>the name of function ? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/boundsj/ObjectiveDDP/issues/130#issuecomment-92715395

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by ducmaxime** [comment]
It's ok for me !!!! Thanks

**Comment by mikey0000** [comment]
No problem, remember I’m usually in gitter so hit me up in there for these kind of issues and also means the community can help too.
