### ISSUE TITLE
Insert Issue

### ISSUE THREAD

**Issue by kevinpk999** [boundsj/ObjectiveDDP#133]
After subscribing to a DDP feed for my "tasks", when I try to insert (create) a new task with teh below format, I receive a <b>"Meteor.error Invalid[400]"</b>  error message.  Does this mean my server is rejecting my insert attempt due to some issue with my object's parameters?

[self.meteor callMethodName:@"/tasks/insert"
                 parameters:parameters
           responseCallback:nil];

Note, the on the same feed, the corresponding update call is working as expected.

Thanks.

**Comment by mikey0000** [comment]
Yes, it does, please use gitter for help as opposed to the issues tab, thanks
