### ISSUE TITLE
support meteor-publish-composite

### ISSUE THREAD

**Issue by anderson916** [boundsj/ObjectiveDDP#135]
Thank you very much for this wonderful library. I cannot get any data when I use meteor-publish-composite in the server side. But it works if I use standard publish method. 

Will you support meteor-publish-composite? Is it difficult?

Thanks again.

**Comment by mikey0000** [comment]
Not at this point in time. This library supports the DDP protocol so if another library doesn’t work, you should take it up with them to support it. Of course your more than welcome to submit pull requests.
