### ISSUE TITLE
cannot logon without any subscription

### ISSUE THREAD

**Issue by anderson916** [boundsj/ObjectiveDDP#136]
Hi there,

after I construct the MeteorClient, I cannot login with MeteorClient.logonWithEmail. But if I subscribe to a collection, it works. 

Can you explain? Or is it a bug? 

Thanks.

**Comment by mikey0000** [comment]
Check how the example apps work, its just a timing thing

if you use an actual form to login you’ll see it will work fine.

**Comment by anderson916** [comment]
Yes, I followed the example. But you subscribe two collections before logon. So this is  my question. Is it a must we should subscribe  some collections before using logon methods.

**Comment by mikey0000** [comment]
No it is not.
