### ISSUE TITLE
-[MeteorClient init]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by Dids** [boundsj/ObjectiveDDP#143]
Bare minimum setup, followed the pod-based setup as closely as possible.
After I try to initialize MeteorClient, it crashes. Targeting iOS 7.1, running on Yosemite and using latest version of Xcode.

Any ideas?

**Comment by mikey0000** [comment]
Using Swift or Objective C? Make sure you follow the example projects. Best bet is to start with the sample projects and see if it still crashes. Unfortunately at this time you have to initialise it in the appDelegate file.

**Comment by Dids** [comment]
Objective-C and I'm initializing it in AppDelegate (as a strong property). I'll have a look at the example projects, maybe I missed a step.

**Comment by Dids** [comment]
Got it. According to the docs, a regular init should work (or [MeteorClient new]), but it seems like initWithDDPVersion needs to be used instead (there's no default init?).

I'll close this, since it's solved.
