### ISSUE TITLE
logonWithSessionToken to resume session

### ISSUE THREAD

**Issue by kormic** [boundsj/ObjectiveDDP#159]
Hello there, I am trying to use this method in order to resume the session for the user. I keep the token using nsuserdefaults and on viewWillAppear I call logonWithSessionToken but I get this error:

error!!! Error Domain=boundsj.objectiveddp.transport Code=0 "You are not connected" UserInfo={NSLocalizedDescription=You are not connected}

On initialiseMeteor I use pre2. Any ideas?

**Comment by mikey0000** [comment]
That error means the websocket is no longer connected, are you able to confirm that the connection is active? Can you give me a run down of the scenario?

**Comment by kormic** [comment]
I think you are right!!! I try to do this in viewWillAppear but when logonWithSessionToken is taking place the connection in not yet ready....I put it in viewWillDisappear just to check and it connects just fine! I must check this a little more but I m 99% sure that this is the problem. If I have any other problems I will let you know....

**Comment by kormic** [comment]
OK, I am trying to find out when the meteor is connected and I can't figure it out. I have tried in didFinishLaunchingWithOptions, viewWillAppear, viewDidAppear, applicationDidBecomeActive..... actually everywhere! The only way I can logonWIthSessionToken is if I do it with a button (just to see if it works), and also when the app "returns" from "somewhere", in example if I logonWithSessionToken in applicationDidEnterForeground then when I go to Home and then open the app again then it logons. When does the meteorClient.connected in the app lifecycle becomes true?

Thanks in advance....

**Comment by mikey0000** [comment]
you may want to attempt using
```
reconnect
```
Someone else had this issue as well, I might look into a delegate for when meteor connects to the server.
The big parts all happen in the app delegate.

**Comment by kormic** [comment]
I think I tried that too. The thing is that everything can happen after the view is completely load. What I did for now is create an empty view controller and on viewDidAppear of that viewcontroller I performSegueWithIdentifier and on viewDidDisappear I logonWithSessionToken. On the login view controller on viewDidAppear I check the AuthState and then I go on from there. This is a workaround but the bad thing is that the user get's to see the login view for a second... The main thing is that the logonWithSessionToken can happen only after everything is done with the view, and when I say after I mean even after viewDidAppear!!! Does this make sense?

**Comment by mikey0000** [comment]
Yes it does, have you tried anything in the app Delegate?

**Comment by kormic** [comment]
The initialiseMeteor is in appDelegate also I am adding observers in there. The only thing that happens in the viewWillAppear is the logonWithSessionToken. I also tried the logonWithSessionToken in the appDelegate but still it says I am not yet connected. I also tried to logonWithSessionToken in the function the observer calls when MeteorClientDidConnectNotification (it's in the appDelegate also).

**Comment by kormic** [comment]
Hello again! I don't know if my edit in my comment above is correct. I don't see why when I try to logon in the appdelegate I get the error and when I try to logon a little bit later I can do ti successfully....
