### ISSUE TITLE
swift example - swift 2.0

### ISSUE THREAD

**Issue by kormic** [boundsj/ObjectiveDDP#160]
Hello there, I tried to run the swift example but It won't build as it's not swift 2 compatible. I fixed a few things and for me now it's building and running on Xcode 7 and swift 2. Should I do a pull request?

P.S. > Everything seems to be working except on sharing I get a Meteor Todos alert "Access denied ...." . I guess this is right (?)

**Comment by mikey0000** [comment]
yes please, yes that is fine.
