### ISSUE TITLE
Can't connect to server (meteor 1.2.0.2)

### ISSUE THREAD

**Issue by kormic** [boundsj/ObjectiveDDP#162]
Now that rocket.chat has updated meteor to 1.2.0.2 (from 1.1.0.3) I can't seem to connect to the server. Could be rocket.chat's problem?

**Comment by mikey0000** [comment]
will it connect to a pure meteor 1.2 install ?

**Comment by kormic** [comment]
I m sorry! I had to put /websocket at the end of the url. It works fine.
