### ISSUE TITLE
Create collection from the client side

### ISSUE THREAD

**Issue by kormic** [boundsj/ObjectiveDDP#164]
Ok, this might be a stupid question because I am a total noob on Meteor but is it possible to create a collection from the client? I know (at least I think I know) that when running new Meteor.collection("example"), a new collection is being created. But is it possible to do that from the client side(meaning within the app)?

If my question is not "right" please let me know!

**Comment by mikey0000** [comment]
Hi @kormic you'll need to create a meteor method and call that from iOS/OSX/client you can't directly access meteorjs. I'd have a read over the DDP protocol specification to gain a better understanding of what DDP actually does.

The only stupid question is the one not asked! :+1:

**Comment by kormic** [comment]
Hello again! Do we have any update on this? I have a client (web browser) that calls this

@ChatMessage = new Meteor.Collection null

That collection is being created in minimongo and the server then "feeds" it with messages. Is it possible to do this from the iOS client?

**Comment by mikey0000** [comment]
in short when you create a collection on the client side it is also created server side, What you want to do is create a meteor method which creates the collection then subscribe to it. You can not directly access meteors methods over DDP.

e.g
```
Meteor.methods = {
//create collection
}
```

then call it from the client
then subscribe to it.

**Comment by kormic** [comment]
Unfortunately I am not responsible from the server so I can't modify the code...I guess I have to ask the server guys...Thanks anyways!!! :)
