### ISSUE TITLE
callMethodName with NSDate as a parameter

### ISSUE THREAD

**Issue by kormic** [boundsj/ObjectiveDDP#165]
I would like to call a method with a parameter NSDate. Not string or timestamp. This is because the server side handles timestamps as "new Date()" and if I send a string or timestamp it doesn't work. Is this possible?

Thanks once again...

**Comment by mikey0000** [comment]
have a good read of this https://github.com/meteor/meteor/blob/devel/packages/ddp/DDP.md
specifically this
Appendix: EJSON

it tells you how to transfer dates correctly across DDP.
```
{"$date": MILLISECONDS_SINCE_EPOCH}
```
so in your dictionary you have $date : value

**Comment by kormic** [comment]
Thank you!!! :) You saved my day!!!
