### ISSUE TITLE
CollectionFS with ObjectiveDDP

### ISSUE THREAD

**Issue by ivangonzalez** [boundsj/ObjectiveDDP#57]
Hi, is possible use CollectionFS with objective DDP?
I don't know how can I call the methods of CollectionFS.
Thanx

**Comment by bitomule** [comment]
Any update on this? I need to upload files from iOS app to a Meteor app. If DDP isn't the best option, any idea on how to do it with a POST request?

**Comment by mikey0000** [comment]
Read the comments, it's been solved

**Comment by bitomule** [comment]
@mikey0000 is it possible to upload big files and non images?

**Comment by mikey0000** [comment]
How big is big? Ultimately it is binary data so the answer should be yes. 

On 12 March 2015 8:45:46 am NZDT, bitomule <notifications@github.com> wrote:
>@mikey0000 is it possible to upload big files and non images?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/boundsj/ObjectiveDDP/issues/57#issuecomment-78354892

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by bitomule** [comment]
@mikey0000 we wan't to allow as much as we can to the end user but it would give problems if big files aren't chunked no?

**Comment by mikey0000** [comment]
Your correct, you should be able to create a simple chunking algorithm and split the data into fixed lengths then put it back together on the server. Not my field of expertise so how you go about this I'm not sure. 

On 12 March 2015 8:51:55 am NZDT, bitomule <notifications@github.com> wrote:
>@mikey0000 we wan't to allow as much as we can to the end user but it
>would give problems if big files aren't chunked no?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/boundsj/ObjectiveDDP/issues/57#issuecomment-78356795

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by bitomule** [comment]
Thanks @mikey0000 , hope anyone here can help me with the chunking to upload. I don't know how to do it :(

**Comment by mikey0000** [comment]
@bitomule is this an open or closed source project, I'd be interested in helping what I can (which is not much unfortunately ) I like a good challenge and I have a fair idea how I would do it too.

**Comment by bitomule** [comment]
@mikey0000 The app is closed source but it is possible to open source the file uploading part. Right now I'm only trying to do the "simple" upload with an image.

**Comment by mikey0000** [comment]
Well let me know when you want a hand.

**Comment by bitomule** [comment]
Ok, I have it working following this example and works with any file (just tested with small ones).

**Comment by bitomule** [comment]
I've chunking working but for some reason it doesn't work with big files on nitrous.io servers. I'm going to try on a real server.

Here's my swift controller:

https://gist.github.com/bitomule/6fe5563e43031c06de3b

And the iron router server route that saves the file:

https://gist.github.com/bitomule/3ffb03704f5caa9c41fe

The max size I've tested and worked is 5mb.

**Comment by Romerio** [comment]
Thanxs @ewindso
