### ISSUE TITLE
Callback API for data updates

### ISSUE THREAD

**Issue by boundsj** [boundsj/ObjectiveDDP#67]
Integrate RBHive and expose callback API for add / update / delete of documents in collections. "deprecate" the NSNotification center API for same.

**Comment by aspin** [comment]
More of a question than a fix or anything, but just in case I'm misreading --- ObjectiveDDP does not yet get any information about the actual changes/insertions/removals when listening for updates about a specific collection, right?

**Comment by mikey0000** [comment]
yes it does but it does it through notifications assuming you've subscribed to that collection.

**Comment by aspin** [comment]
What and how many argument types do you get back?

**Comment by mikey0000** [comment]
read the wiki https://github.com/boundsj/ObjectiveDDP/wiki
